/* ═══════════════════════════════════════════════════════
   CrewAI RAG + AdSense Dashboard — app.js
   Full interactive logic:
     · Tab navigation
     · Dynamic config.yaml generation
     · Console with log system
     · AdSense OAuth2 bind simulation
     · Ledger table with pagination
     · Toast notifications
   ═══════════════════════════════════════════════════════ */

'use strict';

// Authentication disabled - Direct access to dashboard

/* ─────────────────────────────────────────
   API CONFIGURATION (FOR HOSTINGER / REMOTE DEPLOYMENT)
   Paste your ngrok or localtunnel URL here! (No trailing slash)
   Example: const API_BASE_URL = 'https://modern-bear-123.loca.lt';
   Keep it empty ('') if running locally.
   ───────────────────────────────────────── */
const API_BASE_URL = 'http://localhost:8000';


/* ─────────────────────────────────────────
   STATE
   ───────────────────────────────────────── */
const state = {
  activeTab: 'rag-config',
  consoleLogs: [],
  activeFilter: 'all',
  consoleConnected: false,
  adSenseConnected: false,
  ledgerPage: 1,
  ledgerPerPage: 10,
  ledgerData: [],
  // Chat history
  chatHistory: [],
  sessionCount: 1,
  lastCleared: null,
  // Modal
  pendingClearType: null,
};

/* ─────────────────────────────────────────
   INIT
   ───────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', () => {
  initNav();
  initConfig();
  initConsole();
  initLedger();
  initFilterBtns();
  initSettings();

  // Greet
  appendLog('info', 'CrewAI RAG Dashboard initialized.');
  appendLog('info', 'Waiting for configuration...');
});

/* ─────────────────────────────────────────
   NAVIGATION
   ───────────────────────────────────────── */
const TAB_META = {
  'rag-config': { title: 'RAG Pipeline Config', subtitle: 'Configure your CrewAI retrieval-augmented generation setup' },
  'agents': { title: 'Agents Config', subtitle: 'Define and tune your CrewAI multi-agent team' },
  'console': { title: 'Console', subtitle: 'Live output and command execution for CrewAI pipelines' },
  'adsense-bind': { title: 'Bind AdSense Account', subtitle: 'Connect your Google AdSense account via OAuth2' },
  'ledger': { title: 'Earnings Ledger', subtitle: 'View your Google AdSense revenue history and analytics' },
  'retrieval': { title: 'Retrieval Config', subtitle: 'Configure document ingestion, chunking, embedding and top-K search' },
  'aggregation': { title: 'Aggregation Config', subtitle: 'Define how retrieved chunks are merged and ranked before LLM generation' },
  'settings': { title: 'Settings', subtitle: 'Global configuration, clear chat history, and logging options' },
};

function initNav() {
  document.querySelectorAll('.nav-item').forEach(link => {
    link.addEventListener('click', e => {
      e.preventDefault();
      const tab = link.dataset.tab;
      if (tab) switchTab(tab);
    });
  });
}

function switchTab(tabId) {
  state.activeTab = tabId;

  document.querySelectorAll('.nav-item').forEach(l => l.classList.toggle('active', l.dataset.tab === tabId));
  document.querySelectorAll('.tab-panel').forEach(p => p.classList.toggle('active', p.id === `tab-${tabId}`));

  const meta = TAB_META[tabId] || {};
  document.getElementById('page-title').textContent = meta.title || '';
  document.getElementById('page-subtitle').textContent = meta.subtitle || '';
}

/* ─────────────────────────────────────────
   CONFIG YAML GENERATION
   ───────────────────────────────────────── */
function initConfig() {
  updateConfig();
  // Live update on any input change
  document.querySelectorAll('#tab-rag-config input, #tab-rag-config select').forEach(el => {
    el.addEventListener('input', updateConfig);
  });
}

function updateConfig() {
  const provider = val('llm-provider') || 'google';
  const model = val('llm-model') || 'gemini-2.0-flash';
  const temp = val('llm-temp') || '0.1';
  const tokens = val('llm-tokens') || '4096';
  const vstore = val('vector-store') || 'chroma';
  const collName = val('collection-name') || 'crewai_rag_docs';
  const emb = val('embed-model') || 'text-embedding-3-small';
  const chunk = val('chunk-size') || '512';
  const overlap = val('chunk-overlap') || '64';

  const sources = Array.from(document.querySelectorAll('.source-path')).map(s => s.textContent);
  const srcYaml = sources.map(s => `    - "${s}"`).join('\n');

  const yaml = `# CrewAI RAG Configuration
# Generated by CrewAI RAG Dashboard
# ${new Date().toISOString()}

llm:
  provider: ${provider}
  model: ${model}
  temperature: ${temp}
  max_tokens: ${parseInt(tokens)}
  streaming: true

embeddings:
  model: ${emb}

vector_store:
  type: ${vstore}
  collection: ${collName}
  persist_directory: ./chroma_db

rag:
  chunk_size: ${parseInt(chunk)}
  chunk_overlap: ${parseInt(overlap)}
  top_k: 5
  similarity_threshold: 0.7
  sources:
${srcYaml || '    # No sources added yet'}

crew:
  process: sequential
  memory: true
  cache: true
  max_rpm: 10
  verbose: true

adsense:
  client_id: \${GOOGLE_ADSENSE_CLIENT_ID}
  client_secret: \${GOOGLE_ADSENSE_CLIENT_SECRET}
  redirect_uri: \${GOOGLE_ADSENSE_REDIRECT_URI}
  scopes:
    - https://www.googleapis.com/auth/adsense.readonly
    - https://www.googleapis.com/auth/adsense
`;

  const el = document.getElementById('config-preview');
  if (el) el.textContent = yaml;
}

function val(id) {
  const el = document.getElementById(id);
  return el ? el.value : '';
}

function copyConfig() {
  const text = document.getElementById('config-preview').textContent;
  navigator.clipboard.writeText(text).then(() => showToast('Copied config.yaml to clipboard!', 'success'));
}

function saveConfig() {
  updateConfig();
  appendLog('success', 'Configuration saved successfully.');
  showToast('Config saved!', 'success');
  // Flash the preview border
  const el = document.getElementById('config-preview');
  if (el) {
    el.style.borderColor = '#10b981';
    setTimeout(() => el.style.borderColor = '', 800);
  }
}

/* ─────────────────────────────────────────
   DOCUMENT SOURCES
   ───────────────────────────────────────── */
function addSource() {
  const type = document.getElementById('new-source-type').value;
  const path = document.getElementById('new-source-path').value.trim();
  if (!path) { showToast('Please enter a path or URL.', 'error'); return; }

  const item = document.createElement('div');
  item.className = 'source-item';
  const badgeClass = `badge-${type.toLowerCase()}`;
  item.innerHTML = `
    <span class="source-type-badge ${badgeClass}">${type}</span>
    <span class="source-path">${escapeHtml(path)}</span>
    <button class="remove-source" onclick="removeSource(this)">x</button>`;
  document.getElementById('source-list').appendChild(item);
  document.getElementById('new-source-path').value = '';
  updateConfig();
  appendLog('info', `Source added: [${type}] ${path}`);
  showToast(`Added ${type} source`, 'success');
}

function removeSource(btn) {
  const item = btn.closest('.source-item');
  const path = item.querySelector('.source-path').textContent;
  item.style.opacity = '0';
  item.style.transform = 'translateX(8px)';
  item.style.transition = '.2s ease';
  setTimeout(() => { item.remove(); updateConfig(); }, 200);
  appendLog('warn', `Source removed: ${path}`);
}

/* ─────────────────────────────────────────
   CONSOLE
   ───────────────────────────────────────── */
const MOCK_COMMANDS = {
  'crewai run': [
    { type: 'info', msg: 'Starting CrewAI crew...' },
    { type: 'info', msg: 'Initializing RAG pipeline with ChromaDB...' },
    { type: 'info', msg: 'Loading embeddings model: text-embedding-3-small' },
    { type: 'success', msg: 'Vector store loaded. 1,248 documents indexed.' },
    { type: 'info', msg: 'Agent [Researcher] starting task...' },
    { type: 'info', msg: 'Retrieving top-5 relevant chunks for query...' },
    { type: 'success', msg: 'Researcher Agent completed. 5 chunks retrieved.' },
    { type: 'info', msg: 'Agent [Analyst] analyzing data...' },
    { type: 'success', msg: 'Revenue analysis complete. RPM increased by 12.4%.' },
    { type: 'info', msg: 'Agent [Writer] generating report...' },
    { type: 'success', msg: 'Report generated: adsense_report_oct2026.md' },
    { type: 'success', msg: 'Crew finished in 14.2s. All tasks complete.' },
  ],
  'crewai kickoff': [
    { type: 'info', msg: 'Kicking off CrewAI pipeline...' },
    { type: 'success', msg: 'Pipeline started successfully.' },
  ],
  'help': [
    { type: 'info', msg: 'Available commands: crewai run | crewai kickoff | crewai train | crewai test | clear | help' },
  ],
  'clear': [],
  'crewai train': [
    { type: 'info', msg: 'Training mode enabled. n_iterations=3' },
    { type: 'warn', msg: 'Training may take a while. Running iteration 1/3...' },
    { type: 'success', msg: 'Training complete. Model performance improved by 8.3%.' },
  ],
  'crewai test': [
    { type: 'info', msg: 'Running test suite...' },
    { type: 'success', msg: 'All 12 agent tests passed. 0 failures.' },
  ],
};

function initConsole() {
  appendLog('info', 'Console ready. Type "help" for available commands.');
  appendLog('info', 'RAG pipeline: IDLE');
  appendLog('warn', 'AdSense account not connected.');
  appendLog('success', 'Vector store: ChromaDB loaded.');
}

function appendLog(type, msg) {
  const ts = new Date().toLocaleTimeString('en-US', { hour12: false });
  const log = { type, msg, ts, id: Date.now() + Math.random() };
  state.consoleLogs.push(log);
  renderLog(log);
  updateLogCount();
  // Auto scroll
  const out = document.getElementById('console-output');
  if (out) out.scrollTop = out.scrollHeight;
}

function renderLog(log) {
  if (state.activeFilter !== 'all' && state.activeFilter !== log.type) return;
  const out = document.getElementById('console-output');
  if (!out) return;
  const line = document.createElement('div');
  line.className = 'log-line';
  line.dataset.type = log.type;
  line.innerHTML = `
    <span class="log-ts">${log.ts}</span>
    <span class="log-tag tag-${log.type}">${log.type.toUpperCase()}</span>
    <span class="log-msg msg-${log.type}">${escapeHtml(log.msg)}</span>`;
  out.appendChild(line);
}

function updateLogCount() {
  const el = document.getElementById('log-count');
  if (el) el.textContent = `${state.consoleLogs.length} entries`;
}

function clearConsole() {
  state.consoleLogs = [];
  const out = document.getElementById('console-output');
  if (out) {
    out.innerHTML = '';
    // Add a clear line
    const line = document.createElement('div');
    line.className = 'log-line';
    line.style.justifyContent = 'center';
    line.style.color = 'var(--text-muted)';
    line.style.fontSize = '.7rem';
    line.style.padding = '1rem 0';
    line.textContent = '— Console cleared —';
    out.appendChild(line);
  }
  updateLogCount();
  showToast('Console cleared', 'info');
}

function runConsoleCmd() {
  const input = document.getElementById('console-cmd');
  const cmd = input.value.trim().toLowerCase();
  if (!cmd) return;

  appendLog('info', `$ ${cmd}`);
  input.value = '';

  if (cmd === 'clear') { clearConsole(); return; }

  const steps = MOCK_COMMANDS[cmd];
  if (!steps) {
    appendLog('error', `Command not found: "${cmd}". Type "help" for available commands.`);
    return;
  }

  let delay = 200;
  steps.forEach(step => {
    setTimeout(() => appendLog(step.type, step.msg), delay);
    delay += Math.random() * 500 + 200;
  });
}

function exportLogs() {
  const text = state.consoleLogs.map(l => `[${l.ts}] [${l.type.toUpperCase()}] ${l.msg}`).join('\n');
  downloadText(text, 'crewai_console.log');
  showToast('Logs exported', 'success');
}

function initFilterBtns() {
  document.querySelectorAll('.filter-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      state.activeFilter = btn.dataset.filter;
      rerenderConsole();
    });
  });
}

function rerenderConsole() {
  const out = document.getElementById('console-output');
  if (!out) return;
  out.innerHTML = '';
  state.consoleLogs.forEach(log => {
    if (state.activeFilter === 'all' || state.activeFilter === log.type) renderLog(log);
  });
}

/* ─────────────────────────────────────────
   ADSENSE BIND — DUAL PUBLISHER
   rekyprasetyo446@gmail.com
   pub-5719586361422018  (Primary)
   ───────────────────────────────────────── */

const PUBLISHER_ACCOUNTS = {
  'pub-5719586361422018': {
    label: 'Primary Account',
    gmail: 'rekyprasetyo446@gmail.com',
    name: 'Reky Prasetyo',
    currency: 'USD',
    timezone: 'Asia/Jakarta',
    status: 'Active',
    dotId: 'dot-5719',
    infoId: 'account-info-5719',
    connected: false,
  },
};

let activePubId = 'pub-5719586361422018';

function selectPub(btn, pubId) {
  activePubId = pubId;
  document.querySelectorAll('.pub-tab').forEach(t => t.classList.remove('active'));
  btn.classList.add('active');
  const lbl = document.getElementById('active-pub-label');
  if (lbl) lbl.textContent = `Active: ${pubId}`;
  // Sync the dropdown
  const sel = document.getElementById('pub-id-select');
  if (sel) sel.value = pubId;
}

function onPubIdChange(pubId) {
  activePubId = pubId;
  document.querySelectorAll('.pub-tab').forEach(t => {
    t.classList.toggle('active', t.dataset.pub === pubId);
  });
  const lbl = document.getElementById('active-pub-label');
  if (lbl) lbl.textContent = `Active: ${pubId}`;
}

function addNewPub() {
  showToast('To add a publisher, enter its pub-XXXXXXXX ID and complete OAuth2.', 'info');
}

function switchGoogleAccount() {
  showToast('Switch account: open Google sign-in with a different Gmail address.', 'info');
  appendLog('info', 'User requested Google account switch.');
}

function connectAdSense() {
  const clientId = document.getElementById('client-id').value.trim();
  const clientSecret = document.getElementById('client-secret').value.trim();
  const redirectUri = document.getElementById('redirect-uri').value.trim();
  const gmail = 'rekyprasetyo446@gmail.com';

  if (!clientId || !clientSecret) {
    showToast('Please fill in Client ID and Client Secret first.', 'error');
    document.getElementById('step-1').classList.add('active');
    return;
  }

  const btn = document.getElementById('btn-connect-adsense');
  btn.innerHTML = `<svg width="16" height="16" viewBox="0 0 20 20" fill="none" style="animation:spin .8s linear infinite"><path d="M10 3a7 7 0 11-7 7" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg> Connecting...`;
  btn.disabled = true;

  appendLog('info', `Initiating Google OAuth2 for ${gmail}...`);
  appendLog('info', `Publisher ID: ${activePubId}`);
  appendLog('info', `Client ID: ${clientId.substring(0, 20)}...`);

  setTimeout(() => {
    appendLog('success', 'Authorization endpoint reached.');
    appendLog('info', `Consent screen shown for: ${gmail}`);
  }, 600);

  setTimeout(() => {
    appendLog('success', 'OAuth2 authorization code received.');
    appendLog('info', 'Exchanging authorization code for tokens...');
  }, 1400);

  setTimeout(() => {
    appendLog('success', `Access token granted for ${activePubId}.`);
    appendLog('info', 'Token scope: adsense.readonly, adsense');
    appendLog('info', 'Verifying publisher account...');
  }, 2200);

  setTimeout(() => {
    appendLog('success', `AdSense account VERIFIED: ${activePubId}`);
    appendLog('success', `Bound to Gmail: ${gmail}`);
    bindAccountUI(clientId, clientSecret, redirectUri, activePubId);
    btn.innerHTML = `<svg width="14" height="14" viewBox="0 0 20 20" fill="#10b981"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg> Connected`;
    btn.style.background = '#10b981';
    btn.style.color = 'white';
    btn.disabled = false;
  }, 3200);
}

function bindAccountUI(clientId, clientSecret, redirectUri, pubId) {
  const account = PUBLISHER_ACCOUNTS[pubId];
  if (!account) return;
  account.connected = true;

  // Sidebar status dot
  const sideDot = document.querySelector('.status-dot');
  const sideTxt = document.getElementById('status-text');
  if (sideDot) sideDot.classList.add('connected');
  if (sideTxt) sideTxt.textContent = `Connected (${Object.values(PUBLISHER_ACCOUNTS).filter(a => a.connected).length} pub)`;

  // Per-pub status dot
  const pubDot = document.getElementById(account.dotId);
  if (pubDot) pubDot.classList.add('connected');

  // Per-pub account info card
  const expiryDate = new Date(Date.now() + 3600 * 1000).toLocaleTimeString();
  const fakeToken = 'ya29.' + randomHex(32);
  const fakeRefresh = '1//0g' + randomHex(28);
  const infoEl = document.getElementById(account.infoId);
  if (infoEl) {
    infoEl.innerHTML = `
      <div class="account-connected">
        <div class="account-row">
          <span class="account-row-key">Gmail</span>
          <span class="account-row-val" style="color:var(--cyan)">${account.gmail}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Publisher ID</span>
          <span class="account-row-val" style="font-family:monospace;font-size:.75rem">${pubId}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Account</span>
          <span class="account-row-val">${account.name}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Currency</span>
          <span class="account-row-val">${account.currency}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Timezone</span>
          <span class="account-row-val">${account.timezone}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Status</span>
          <span class="account-row-val green">${account.status}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Token Expires</span>
          <span class="account-row-val">${expiryDate}</span>
        </div>
      </div>`;
  }

  // Mark pub-tab as connected
  document.querySelectorAll('.pub-tab').forEach(t => {
    if (t.dataset.pub === pubId) {
      const idEl = t.querySelector('.pub-tab-id');
      if (idEl && !idEl.textContent.includes('✓')) {
        idEl.innerHTML = `${pubId} <span style="color:var(--green);font-size:.8em">✓</span>`;
      }
    }
  });

  // Update combined .env preview
  const allConnected = Object.entries(PUBLISHER_ACCOUNTS).filter(([, a]) => a.connected);
  const envEl = document.getElementById('env-preview');
  if (envEl) {
    envEl.textContent = `# Google AdSense Credentials (.env)
# Gmail: rekyprasetyo446@gmail.com
# Generated: ${new Date().toISOString()}

GOOGLE_ADSENSE_CLIENT_ID=${clientId}
GOOGLE_ADSENSE_CLIENT_SECRET=GOCSPX-***REDACTED***
GOOGLE_ADSENSE_REDIRECT_URI=${redirectUri}
GOOGLE_ADSENSE_GMAIL=rekyprasetyo446@gmail.com

# Publisher Accounts
GOOGLE_ADSENSE_PUB_PRIMARY=pub-5719586361422018
GOOGLE_ADSENSE_PUB_SECONDARY=
GOOGLE_ADSENSE_ACTIVE_PUB=${pubId}

# Tokens (auto-refreshed — do NOT commit)
GOOGLE_ADSENSE_ACCESS_TOKEN=${fakeToken}
GOOGLE_ADSENSE_REFRESH_TOKEN=${fakeRefresh}`;
  }

  showToast(`${pubId} bound to rekyprasetyo446@gmail.com`, 'success');

  // Re-check chat config state now that a publisher is bound
  checkAdSenseConfig();

  // If only one pub connected so far, auto-trigger second
  const connectedCount = Object.values(PUBLISHER_ACCOUNTS).filter(a => a.connected).length;
  if (connectedCount === 1) {
    const otherPubId = Object.keys(PUBLISHER_ACCOUNTS).find(k => k !== pubId);
    setTimeout(() => {
      appendLog('info', `Auto-binding secondary account: ${otherPubId}...`);
    }, 400);
    setTimeout(() => {
      PUBLISHER_ACCOUNTS[otherPubId].connected = true;
      const otherDot = document.getElementById(PUBLISHER_ACCOUNTS[otherPubId].dotId);
      if (otherDot) otherDot.classList.add('connected');
      bindSecondaryAccountUI(otherPubId, clientId, redirectUri);
      appendLog('success', `Secondary account bound: ${otherPubId}`);
      if (sideTxt) sideTxt.textContent = '2 publishers connected';
    }, 1800);
  }
}

function bindSecondaryAccountUI(pubId, clientId, redirectUri) {
  const account = PUBLISHER_ACCOUNTS[pubId];
  const fakeToken2 = 'ya29.' + randomHex(32);
  const fakeRefresh2 = '1//0g' + randomHex(28);
  const expiryDate2 = new Date(Date.now() + 3600 * 1000).toLocaleTimeString();
  const infoEl2 = document.getElementById(account.infoId);
  if (infoEl2) {
    infoEl2.innerHTML = `
      <div class="account-connected">
        <div class="account-row">
          <span class="account-row-key">Gmail</span>
          <span class="account-row-val" style="color:var(--cyan)">${account.gmail}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Publisher ID</span>
          <span class="account-row-val" style="font-family:monospace;font-size:.75rem">${pubId}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Currency</span>
          <span class="account-row-val">${account.currency}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Status</span>
          <span class="account-row-val green">${account.status}</span>
        </div>
        <div class="account-row">
          <span class="account-row-key">Token Expires</span>
          <span class="account-row-val">${expiryDate2}</span>
        </div>
      </div>`;
  }
  document.querySelectorAll('.pub-tab').forEach(t => {
    if (t.dataset.pub === pubId) {
      const idEl = t.querySelector('.pub-tab-id');
      if (idEl && !idEl.textContent.includes('✓')) {
        idEl.innerHTML = `${pubId} <span style="color:var(--green);font-size:.8em">✓</span>`;
      }
    }
  });
  // Update .env with both tokens
  const envEl = document.getElementById('env-preview');
  if (envEl) {
    envEl.textContent += `\n\n# Secondary publisher tokens\nGOOGLE_ADSENSE_ACCESS_TOKEN_SECONDARY=${fakeToken2}\nGOOGLE_ADSENSE_REFRESH_TOKEN_SECONDARY=${fakeRefresh2}`;
  }
  showToast('Both publishers connected!', 'success');
}

function copyEnv() {
  const text = document.getElementById('env-preview').textContent;
  navigator.clipboard.writeText(text).then(() => showToast('Copied .env to clipboard!', 'success'));
}


/* ─────────────────────────────────────────
   LEDGER
   ───────────────────────────────────────── */
function initLedger() {
  state.ledgerData = generateLedgerData();
  renderLedger();
}

function generateLedgerData() {
  const units = ['Header Banner', 'Sidebar Right', 'In-Article', 'Footer Ad', 'Mobile Anchor', 'Sticky Rail'];
  const sources = ['Google Search', 'Direct App Traffic', 'Social Referral', 'Web Crawlers', 'Push Notifications'];
  const data = [];
  for (let d = 1; d <= 30; d++) {
    const date = `2026-10-${String(d).padStart(2, '0')}`;
    const unit = units[Math.floor(Math.random() * units.length)];
    const source = sources[Math.floor(Math.random() * sources.length)];
    const impressions = Math.floor(Math.random() * 18000 + 5000);
    const clicks = Math.floor(impressions * (Math.random() * 0.015 + 0.005));
    const ctr = (clicks / impressions * 100).toFixed(2);
    const rpm = (Math.random() * 4 + 1.5).toFixed(2);
    const earnings = (impressions / 1000 * parseFloat(rpm)).toFixed(2);
    const status = d <= 25 ? 'finalized' : 'estimated';
    data.push({ date, unit, source, impressions, clicks, ctr, rpm, earnings, status });
  }
  return data.sort((a, b) => b.date.localeCompare(a.date));
}

function renderLedger() {
  const tbody = document.getElementById('ledger-body');
  if (!tbody) return;
  tbody.innerHTML = '';

  const start = (state.ledgerPage - 1) * state.ledgerPerPage;
  const slice = state.ledgerData.slice(start, start + state.ledgerPerPage);

  slice.forEach(row => {
    const tr = document.createElement('tr');
    tr.innerHTML = `
      <td>${row.date}</td>
      <td><span style="opacity:0.7; font-family:'JetBrains Mono', monospace; font-size:12px;">${row.account || 'pub-5719586361422018'}</span></td>
      <td>${row.unit}</td>
      <td><span style="opacity:0.8; font-size:12px; font-weight: 500;">${row.source}</span></td>
      <td>${row.impressions.toLocaleString()}</td>
      <td>${row.clicks.toLocaleString()}</td>
      <td>${row.ctr}%</td>
      <td>$${row.rpm}</td>
      <td class="earn">$${row.earnings}</td>
      <td><span class="ledger-status status-${row.status}">${row.status.toUpperCase()}</span></td>`;
    tbody.appendChild(tr);
  });

  // Pagination
  const total = state.ledgerData.length;
  const pages = Math.ceil(total / state.ledgerPerPage);
  const infoEl = document.getElementById('ledger-info');
  if (infoEl) infoEl.textContent = `Showing ${start + 1}–${Math.min(start + state.ledgerPerPage, total)} of ${total} entries`;

  const pagEl = document.getElementById('pagination');
  if (pagEl) {
    pagEl.innerHTML = '';
    
    // Prev Button
    const prevBtn = document.createElement('button');
    prevBtn.className = 'page-btn';
    prevBtn.innerHTML = '&laquo; Prev';
    prevBtn.disabled = state.ledgerPage === 1;
    prevBtn.onclick = () => { if (state.ledgerPage > 1) { state.ledgerPage--; renderLedger(); } };
    pagEl.appendChild(prevBtn);

    for (let i = 1; i <= pages; i++) {
      const btn = document.createElement('button');
      btn.className = `page-btn${i === state.ledgerPage ? ' active' : ''}`;
      btn.textContent = i;
      btn.onclick = () => { state.ledgerPage = i; renderLedger(); };
      pagEl.appendChild(btn);
    }
    
    // Next Button
    const nextBtn = document.createElement('button');
    nextBtn.className = 'page-btn';
    nextBtn.innerHTML = 'Next &raquo;';
    nextBtn.disabled = state.ledgerPage === pages;
    nextBtn.onclick = () => { if (state.ledgerPage < pages) { state.ledgerPage++; renderLedger(); } };
    pagEl.appendChild(nextBtn);
  }
}

function refreshLedger() {
  state.ledgerData = generateLedgerData();
  state.ledgerPage = 1;
  renderLedger();
  showToast('Mock ledger generated', 'info');
}

async function syncRealLedger() {
  const btn = document.querySelector('button[onclick="syncRealLedger()"]');
  if (btn) {
    btn.textContent = 'Authenticating with Google...';
    btn.disabled = true;
  }

  try {
    const client = google.accounts.oauth2.initTokenClient({
      client_id: '444612165864-qmq302s5aocsh3ma40gg1dgudb5uc10f.apps.googleusercontent.com',
      scope: 'https://www.googleapis.com/auth/adsense.readonly',
      callback: async (tokenResponse) => {
        if (tokenResponse.error !== undefined) {
          if (btn) {
            btn.textContent = 'Sync Google AdSense';
            btn.disabled = false;
          }
          throw new Error(tokenResponse.error);
        }

        try {
          if (btn) {
            btn.textContent = 'Fetching AdSense Data...';
          }
          
          const res = await fetch('https://adsense.googleapis.com/v2/accounts', {
            headers: {
              'Authorization': `Bearer ${tokenResponse.access_token}`
            }
          });
          
          if (!res.ok) {
            throw new Error(`Google API Error: ${res.statusText}`);
          }
          
          const accountsData = await res.json();

          if (!accountsData.accounts || accountsData.accounts.length === 0) {
            throw new Error("No AdSense accounts found for this user.");
          }

          const accountName = accountsData.accounts[0].name;
          const publisherId = accountName.replace('accounts/', '');

          state.ledgerData = [{
            date: new Date().toISOString().split('T')[0],
            account: publisherId,
            unit: 'Google Ad Web Sync',
            source: 'Google AdSense API (Direct JS)',
            impressions: 0,
            clicks: 0,
            ctr: '0.00',
            rpm: '0.00',
            earnings: '0.00',
            status: 'success'
          }];

          state.ledgerPage = 1;
          renderLedger();

          appendLog('success', 'Real AdSense earnings synced securely from the browser!');
          showToast('Real Earnings Synced', 'success');
        } catch (err) {
          console.error(err);
          appendLog('error', 'AdSense Fetch Failed: ' + err.message);
          showToast('Sync Failed. See console.', 'error');
        } finally {
          if (btn) {
            btn.textContent = 'Sync Google AdSense';
            btn.disabled = false;
          }
        }
      },
    });
    
    client.requestAccessToken({ prompt: 'consent' });
  } catch (err) {
    console.error(err);
    appendLog('error', 'OAuth Initialization Failed: ' + err.message);
    showToast('OAuth Failed', 'error');
    if (btn) {
      btn.textContent = 'Sync Google AdSense';
      btn.disabled = false;
    }
  }
}

function exportLedger() {
  const header = 'Date,Ad Unit,Impressions,Clicks,CTR,RPM,Earnings,Status';
  const rows = state.ledgerData.map(r =>
    `${r.date},${r.unit},${r.impressions},${r.clicks},${r.ctr}%,${r.rpm},${r.earnings},${r.status}`
  );
  downloadText([header, ...rows].join('\n'), 'adsense_ledger.csv');
  showToast('Ledger exported as CSV', 'success');
}

/* ─────────────────────────────────────────
   CREWAI CHAT & CONFIG CHECKER
   ───────────────────────────────────────── */
let chatCheckTimer = null;

function initChatInterface() {
  checkAdSenseConfig();
  // Set up enter key for chat input
  const input = document.getElementById('chat-input-field');
  if (input) {
    input.addEventListener('keypress', function (e) {
      if (e.key === 'Enter') sendChatMessage();
    });
  }
}

function checkAdSenseConfig() {
  const statusEl = document.getElementById('chat-config-status');
  const inputEl = document.getElementById('chat-input-field');
  const btnEl = document.getElementById('chat-send-btn');
  const winEl = document.getElementById('chat-window');

  if (!statusEl || !inputEl) return;

  // Simulate checking for pub-5719586361422018
  const primaryPub = PUBLISHER_ACCOUNTS['pub-5719586361422018'];

  if (primaryPub && primaryPub.connected) {
    statusEl.innerHTML = `<svg width="12" height="12" viewBox="0 0 20 20" fill="currentColor" style="display:inline;vertical-align:middle;margin-right:2px"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg> pub-5719... Active`;
    statusEl.style.background = 'rgba(16,185,129,0.1)';
    statusEl.style.color = 'var(--green)';
    statusEl.style.border = '1px solid rgba(16,185,129,0.3)';

    inputEl.disabled = false;
    btnEl.disabled = false;

    // Welcome message if window only has the loading message
    if (winEl && winEl.children.length === 1 && winEl.children[0].classList.contains('system')) {
      winEl.innerHTML = `
        <div class="chat-msg bot">
          <div class="chat-bubble">Hello! I'm your CrewAI AdSense Assistant. I see <b>pub-5719586361422018</b> is connected. You can ask me to analyze your earnings ledger, compare RPMs, or retrieve Google AdSense policies.</div>
        </div>
      `;
    }
  } else {
    statusEl.innerHTML = `Missing pub-5719... Config`;
    statusEl.style.background = 'rgba(248,113,113,0.1)';
    statusEl.style.color = '#f87171';
    statusEl.style.border = '1px solid rgba(248,113,113,0.3)';

    inputEl.disabled = true;
    btnEl.disabled = true;

    if (winEl && winEl.children.length === 1 && winEl.children[0].classList.contains('system')) {
      winEl.children[0].querySelector('.chat-bubble').innerHTML = `
        <span style="color:#f87171">Connection Refused</span><br/>
        Cannot initialize CrewAI agents.<br/>
        Primary Publisher ID (pub-5719586361422018) is not authorized.<br/><br/>
        <a href="#bind" onclick="switchTab('adsense-bind')" style="color:var(--cyan);text-decoration:underline;cursor:pointer">Go to Bind Account tab</a> to authenticate.
      `;
    }
  }
}

function sendChatMessage() {
  const inputEl = document.getElementById('chat-input-field');
  const winEl = document.getElementById('chat-window');
  if (!inputEl || !winEl || !inputEl.value.trim()) return;

  const msg = inputEl.value.trim();
  inputEl.value = '';
  inputEl.disabled = true;
  document.getElementById('chat-send-btn').disabled = true;

  // Add User message
  const userDiv = document.createElement('div');
  userDiv.className = 'chat-msg user';
  userDiv.innerHTML = `<div class="chat-bubble">${escapeHtml(msg)}</div>`;
  winEl.appendChild(userDiv);
  winEl.scrollTop = winEl.scrollHeight;

  // Add Bot typing indicator
  const botDiv = document.createElement('div');
  botDiv.className = 'chat-msg bot';
  botDiv.innerHTML = `<div class="chat-bubble"><span style="animation:pulse 1s infinite">CrewAI is analyzing ledger data...</span></div>`;
  winEl.appendChild(botDiv);
  winEl.scrollTop = winEl.scrollHeight;

  // Simulate API delay
  setTimeout(() => {
    botDiv.innerHTML = `<div class="chat-bubble">
      Based on the retrieved context for <b>pub-5719586361422018</b>:<br/><br/>
      I analyzed your ledger and noticed that your RPM dropped primarily on the "Mobile Anchor" ad unit last Tuesday, likely due to lower advertiser bids in the APAC region. <br/><br/>
      <i>(This is a simulated response. In production, this will hit the CrewAI backend endpoint.)</i>
    </div>`;
    winEl.scrollTop = winEl.scrollHeight;

    inputEl.disabled = false;
    document.getElementById('chat-send-btn').disabled = false;
    inputEl.focus();
  }, 2500);
}


/* ─────────────────────────────────────────
   UTILITIES
   ───────────────────────────────────────── */
function toggleVisibility(inputId, btn) {
  const input = document.getElementById(inputId);
  if (!input) return;
  const isHidden = input.type === 'password';
  input.type = isHidden ? 'text' : 'password';
  btn.style.opacity = isHidden ? '1' : '0.5';
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function randomHex(n) {
  return Array.from({ length: n }, () => Math.floor(Math.random() * 16).toString(16)).join('');
}

let toastTimer = null;
function showToast(msg, type = 'info') {
  const el = document.getElementById('toast');
  if (!el) return;
  if (toastTimer) clearTimeout(toastTimer);
  el.className = `toast toast-${type} show`;
  el.textContent = { success: '✓', error: '✕', info: 'ℹ' }[type] + '  ' + msg;
  toastTimer = setTimeout(() => el.classList.remove('show'), 3000);
}

function downloadText(text, filename) {
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/* ─────────────────────────────────────────
   TAB PANEL DISPLAY FIX
   (handles panels moved outside <main> in markup)
   ───────────────────────────────────────── */
const _origSwitchTab = switchTab;
// Override switchTab to also handle panels with style="display:none"
window.switchTab = function (tabId) {
  // Hide all extra panels
  document.querySelectorAll('.tab-panel').forEach(p => {
    if (p.style.display !== undefined) {
      p.style.display = (p.id === `tab-${tabId}`) ? 'block' : 'none';
    }
    p.classList.toggle('active', p.id === `tab-${tabId}`);
  });
  state.activeTab = tabId;
  document.querySelectorAll('.nav-item').forEach(l =>
    l.classList.toggle('active', l.dataset.tab === tabId));
  const meta = TAB_META[tabId] || {};
  const pt = document.getElementById('page-title');
  const ps = document.getElementById('page-subtitle');
  if (pt) pt.textContent = meta.title || '';
  if (ps) ps.textContent = meta.subtitle || '';

  // Update settings stats when switching to settings tab
  if (tabId === 'settings') renderHistoryStats();
  if (tabId === 'aggregation') initChatInterface();
};

/* ─────────────────────────────────────────
   SETTINGS TAB
   ───────────────────────────────────────── */
function initSettings() {
  // Seed some fake chat history for demonstration
  state.chatHistory = Array.from({ length: 24 }, (_, i) => ({
    id: i,
    role: i % 2 === 0 ? 'user' : 'assistant',
    content: `Message ${i + 1}`,
    ts: new Date(Date.now() - (24 - i) * 60000).toISOString(),
  }));
  state.sessionCount = 3;
  renderHistoryStats();
}

function renderHistoryStats() {
  const msgEl = document.getElementById('hist-msg-count');
  const sessEl = document.getElementById('hist-session-count');
  const sizeEl = document.getElementById('hist-size');
  const clearEl = document.getElementById('hist-last-clear');

  if (msgEl) msgEl.textContent = state.chatHistory.length;
  if (sessEl) sessEl.textContent = state.sessionCount;

  // Approximate size
  const bytes = JSON.stringify(state.chatHistory).length;
  if (sizeEl) sizeEl.textContent = bytes > 1024
    ? `${(bytes / 1024).toFixed(1)} KB`
    : `${bytes} B`;

  if (clearEl) clearEl.textContent = state.lastCleared
    ? new Date(state.lastCleared).toLocaleTimeString()
    : 'Never';
}

/* ─────────────────────────────────────────
   CLEAR HISTORY
   ───────────────────────────────────────── */
function openClearHistoryModal() {
  state.pendingClearType = 'chat';
  const overlay = document.getElementById('clear-history-modal');
  if (overlay) overlay.classList.add('open');
}

function closeClearHistoryModal(event) {
  if (event && event.target !== document.getElementById('clear-history-modal')) return;
  const overlay = document.getElementById('clear-history-modal');
  if (overlay) overlay.classList.remove('open');
  state.pendingClearType = null;
}

function confirmClearHistory() {
  const overlay = document.getElementById('clear-history-modal');
  if (overlay) overlay.classList.remove('open');
  clearChatHistory(state.pendingClearType || 'chat');
  state.pendingClearType = null;
}

/**
 * clearChatHistory(type)
 *  type: 'chat' | 'rag' | 'all'
 */
function clearChatHistory(type) {
  state.lastCleared = new Date().toISOString();

  if (type === 'chat' || type === 'all') {
    state.chatHistory = [];
    appendLog('warn', 'Chat history cleared by user.');
    showToast('Chat history cleared', 'info');
  }

  if (type === 'rag' || type === 'all') {
    appendLog('warn', 'RAG agent memory and embeddings cache reset.');
    showToast('RAG memory cleared', 'info');
  }

  if (type === 'all') {
    state.sessionCount = 0;
    appendLog('warn', 'All sessions wiped. Factory reset complete.');
    showToast('All sessions cleared', 'info');

    // Reset AdSense connection state visually
    const dot = document.querySelector('.status-dot');
    const txt = document.getElementById('status-text');
    if (dot) dot.classList.remove('connected');
    if (txt) txt.textContent = 'Not Connected';
    state.adSenseConnected = false;
  }

  // Animate the clear button
  const btn = document.getElementById('btn-clear-history');
  if (btn) {
    const orig = btn.innerHTML;
    btn.innerHTML = '<svg width="13" height="13" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg> Cleared!';
    btn.style.color = 'var(--green)';
    setTimeout(() => {
      btn.innerHTML = orig;
      btn.style.color = '';
    }, 2000);
  }

  renderHistoryStats();
}

/* Close modal on Escape key */
document.addEventListener('keydown', e => {
  if (e.key === 'Escape') {
    const overlay = document.getElementById('clear-history-modal');
    if (overlay && overlay.classList.contains('open')) {
      overlay.classList.remove('open');
      state.pendingClearType = null;
    }
  }
});

